version: "3.7"
services:

  dev:
    build:
      context: .
      target: dev
    image: fin_dev_image:$VERSION
    container_name: fin_dev
    env_file:
      - .env
    volumes:
      - .:/home/root/app/.
      - vscode-extensions:/root/.vscode-server/extensions
    ports:
      - 8050:8050
    command: bash -c "poetry run python"
    tty: true

  prod:
    build:
      context: .
      target: prod
    image: fin_prod_image:$VERSION
    container_name: fin_prod
    env_file:
      - .env
    ports:
      - 8050:8050
    command: poetry run python app.py

volumes:
  vscode-extensions:
